---

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - qa
  - build
  - release

code_quality:
  stage: qa
  interruptible: true

lint:shellcheck:
  stage: qa
  interruptible: true
  needs: []
  image:
    name: koalaman/shellcheck-alpine
    entrypoint: [""]
  script:
    - shellcheck --format tty $(find -name '*.sh' -type f)

build:
  stage: build
  interruptible: true
  needs: []
  image:
    name: "node:18"
    entrypoint: [""]
  script:
    - ./build.sh

release note:
  stage: qa
  interruptible: true
  script:
    - echo You should write release notes with your changes.
    - exit 1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
      changes:
        paths:
          - releasenotes/**/*
      # Only run (and fail) if no release notes have been written
      when: never

release:
  stage: release
  image: registry.gitlab.com/prologin/tech/tools/renogin:v1.0.0
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - renogin report --version $CI_COMMIT_TAG > changelog_generated.md
  release:
    tag_name: $CI_COMMIT_TAG
    name: $CI_COMMIT_TAG
    description: ./changelog_generated.md
  rules:
    - if: $CI_COMMIT_TAG
